languageCode:           "en"
title:                  "Scoutstrap"
baseURL:                "https://scoutstrap.github.io"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/0.1/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/0.1/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/4.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "A Scout brand theme for Bootstrap"
  authors:              "Scoutstrap and Bootstrap contributors"
  social_image_path:    /docs/4.3/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.3/assets/brand/bootstrap-social-logo.png

  current_version:      "0.1"
  current_bs_version:   "4.3.1"
  rfs_version:          "9.0.2"
  docs_version:         "0.1"
  github_org:           "https://github.com/scoutstrap"
  repo:                 "https://github.com/scoutstrap/scoutstrap"

  download:
    source:             "https://github.com/scoutstrap/scoutstrap/archive/v0.1.1.zip"
    dist:               "https://github.com/scoutstrap/scoutstrap/releases/download/v0.1.1/scoutstrap-0.1.1-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/gh/scoutstrap/scoutstrap@0.1.1/dist/css/scoutstrap.min.css"
    css_hash:         "sha384-P+1bBwoolv4vDCXySfpqUIz3jzeKubfZVhZioiR7mIAc2vHee/EH+BKTspYdfCq4"
    js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    js_hash:          "sha384-vZA7fWbUdVwzQZlO+dkC65mKiaTlKyDvRFeWWT/+J8nBCX0A/OJE2YaFG+m4Zhv0"
    js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-RWMrygDG4kZTKx0uGke0ezaQacpT+TYFYL62nJJ6kpjUYyLxYQ3Vm1QegY1lv6jl"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    popper_hash:      "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
